spring:
  application:
    name: order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/order_sys?characterEncoding=utf-8&userSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
server:
  port: 8002
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #自定义设置随机访问服务规则，默认是轮询